export const WECHAT_PROVIDER = Symbol('WECHAT_PROVIDER');
export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const ACCESS_TOKEN_SERVICE = Symbol('ACCESS_TOKEN_SERVICE');

export const WECHAT_PROVIDER_TOKEN = WECHAT_PROVIDER;
export const USER_REPOSITORY_TOKEN = USER_REPOSITORY;
export const ACCESS_TOKEN_SERVICE_TOKEN = ACCESS_TOKEN_SERVICE;
