export const PLACE_PROVIDER = Symbol('PLACE_PROVIDER');
export const PLACE_REPOSITORY = Symbol('PLACE_REPOSITORY');
export const PLACE_CLOCK = Symbol('PLACE_CLOCK');

export const PLACE_PROVIDER_TOKEN = PLACE_PROVIDER;
export const PLACE_REPOSITORY_TOKEN = PLACE_REPOSITORY;
