export const WEATHER_PROVIDER = Symbol('WEATHER_PROVIDER');
export const CLIMATE_REFERENCE_PROVIDER = Symbol('CLIMATE_REFERENCE_PROVIDER');
export const WEATHER_CACHE_REPOSITORY = Symbol('WEATHER_CACHE_REPOSITORY');
export const WEATHER_CLOCK = Symbol('WEATHER_CLOCK');

export const WEATHER_PROVIDER_TOKEN = WEATHER_PROVIDER;
export const CLIMATE_REFERENCE_PROVIDER_TOKEN = CLIMATE_REFERENCE_PROVIDER;
export const WEATHER_CACHE_REPOSITORY_TOKEN = WEATHER_CACHE_REPOSITORY;
