export const ROUTE_PROVIDER = Symbol('ROUTE_PROVIDER');
export const ROUTE_CACHE_REPOSITORY = Symbol('ROUTE_CACHE_REPOSITORY');
export const ROUTE_CLOCK = Symbol('ROUTE_CLOCK');

export const ROUTE_PROVIDER_TOKEN = ROUTE_PROVIDER;
export const ROUTE_CACHE_REPOSITORY_TOKEN = ROUTE_CACHE_REPOSITORY;
